#  Exploratory Data Analysis (EDA)

Exploratory Data Analysis (EDA) focuses on understanding the structure, quality, and distribution of the dataset stored in the database. It helps in identifying patterns, trends, anomalies, and relationships within the data.  

This analysis also evaluates whether creating aggregated tables is required to support advanced business insights such as:

-  **Vendor Selection for Profitability** – Identifying vendors that contribute the most to revenue and cost efficiency.  
-  **Product Pricing Optimization** – Analyzing pricing patterns to maximize profit margins and competitiveness.

In [1]:
import sqlite3
import pandas as pd

In [2]:
# creating database connection
conn = sqlite3.connect('inventory.db')

In [3]:
# checking tables present in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
tables

              name
0   vendor_invoice
1  begin_inventory
2    end_inventory
3        purchases
4  purchase_prices
5            sales

In [4]:
# exploring what type of data available in the tables
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:',pd.read_sql_query(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql_query(f"select * from {table} limit 5",conn))

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 0

Empty DataFrame
Columns: [InventoryId, Store, Brand, Description, Size, SalesQuantity, SalesDollars, SalesPrice, SalesDate, Volume, Classification, ExciseTax, VendorNo, VendorName]
Index: []

In [5]:
# choosing one vendor and filtering the different tables 
purchases = pd.read_sql_query("select * from purchases where VendorNumber = 4466",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [6]:
vendor_invoice = pd.read_sql_query("""select * from vendor_invoice where VendorNumber = 4466""",conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [15]:
sales_df = pd.read_csv("data/sales.csv")
sales_df.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [2]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("inventory.db")

In [3]:
purchase_prices = pd.read_sql_query(
    "SELECT * FROM purchase_prices WHERE VendorNumber = 4466",
    conn
)

purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [6]:
purchases = pd.read_sql_query("SELECT * FROM purchases", conn)

In [7]:
purchases.groupby(["Brand","PurchasePrice"])[["Quantity","Dollars"]].sum()

                     Quantity   Dollars
Brand PurchasePrice
58    9.28               3550  32944.00
60    7.40               1633  12084.20
61    10.60               312   3307.20
62    28.67              3200  91744.00
63    30.46              2855  86963.30
...                       ...       ...
90089 77.92                32   2493.44
90090 448.27                6   2689.62
90604 78.42               118   9253.56
90609 17.00               321   5457.00
90631 12.74              1938  24690.12

[10664 rows x 2 columns]

## Data Overview

The dataset contains multiple tables storing vendor purchase, pricing, invoice, and sales information.

- **Purchases Table:** Contains vendor purchase transactions including date, brand, quantity, and amount paid.  
- **Purchase Prices Table:** Provides actual product and purchase prices with a unique vendor–brand combination.  
- **Vendor Invoice Table:** Aggregates purchase data with total quantity, purchase amount, and freight cost, unique by vendor and PO number.  
- **Sales Table:** Records sales transactions including brand, quantity sold, selling price, and revenue.

## Summary Table Requirement

Since the required analysis data is distributed across multiple tables, we need to create a consolidated summary table that combines:
- Vendor purchase transactions  
- Sales transaction details  
- Vendor freight costs  
- Actual product pricing  

Next, we will explore each table individually before building the summary table.

In [8]:
freight_summary = pd.read_sql_query("""SELECT 
    VendorNumber, 
    SUM(Freight) as FreightCost 
FROM vendor_invoice 
GROUP BY VendorNumber""", conn)
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [10]:
purchase_summary = pd.read_sql_query("""SELECT 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    p.PurchasePrice,
    pp.Price as ActualPrice,
    pp.Volume,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
WHERE p.PurchasePrice > 0
GROUP BY p.VendorNumber,p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume
ORDER BY TotalPurchaseDollars
""",conn)
purchase_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48
3,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34
4,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64
...,...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60

In [3]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("inventory.db")

In [5]:
purchase_summary = pd.read_sql_query("""
SELECT VendorNumber, Brand,
SUM(Quantity) AS TotalPurchaseQuantity,
SUM(Dollars) AS TotalPurchaseDollars
FROM purchases
GROUP BY VendorNumber, Brand
""", conn)

purchase_summary.head()

   VendorNumber  Brand  TotalPurchaseQuantity  TotalPurchaseDollars
0             2  90085                      8                190.88
1             2  90609                    320               5440.00
2            54    990                      1                105.07
3            60    771                     39                446.16
4            60   3401                      6                 66.60

In [21]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("inventory.db")



purchase_summary = pd.read_sql_query("""
SELECT 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    pp.Volume,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
GROUP BY 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    pp.Volume
LIMIT 10000
""", conn)

In [22]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("inventory.db")

In [23]:
sales_summary = pd.read_sql_query("""
SELECT VendorNo, Brand,
SUM(SalesQuantity) AS TotalSalesQuantity,
SUM(SalesDollars) AS TotalSalesDollars
FROM sales
GROUP BY VendorNo, Brand
LIMIT 10000
""", conn)

In [24]:
vendor_sales_summary = purchase_summary.merge(
    sales_summary,
    left_on=["VendorNumber", "Brand"],
    right_on=["VendorNo", "Brand"],
    how="left"
)

In [25]:
vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    conn,
    if_exists="replace",
    index=False
)

10000

In [17]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Volume',
       'TotalPurchaseQuantity', 'TotalPurchaseDollars', 'VendorNo',
       'TotalSalesQuantity', 'TotalSalesDollars'],
      dtype='object')

## Data Cleaning

Data cleaning ensures the `vendor_sales_summary` table is accurate, consistent, and reliable for analysis and reporting.

### Key Steps
- **Handle Missing Values:** Remove or fill null values in important columns.
- **Remove Duplicates:** Prevent incorrect aggregation and analysis.
- **Standardize Text Fields:** Ensure consistent vendor, brand, and product names.
- **Validate Numerical Data:** Check for negative or invalid values in sales, pricing, and freight.
- **Fix Data Types:** Maintain correct formats for numeric, text, and date columns.

### Outcome
Clean data improves analysis accuracy, speeds up dashboard performance, and supports better vendor and pricing decisions.

In [26]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
VendorNo                 float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
dtype: object

In [27]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
VendorNo                 676
TotalSalesQuantity       676
TotalSalesDollars        676
dtype: int64

In [12]:
vendor_sales_summary.columns

Index(['VendorNumber', 'Brand', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'VendorNo', 'TotalSalesQuantity',
       'TotalSalesDollars'],
      dtype='object')

In [28]:
vendor_sales_summary['VendorName'].unique()

array(['IRA GOLDMAN AND WILLIAMS, LLP          ',
       'AAPER ALCOHOL & CHEMICAL CO', 'ADAMBA IMPORTS INTL INC    ',
       'ALTAMAR BRANDS LLC         ', 'AMERICAN SPIRITS EXCHANGE  ',
       'APPOLO VINEYARDS LLC       ', 'ATLANTIC IMPORTING COMPANY ',
       'BACARDI USA INC            ', 'BANFI PRODUCTS CORP        ',
       'STATE WINE & SPIRITS   ', 'SAZERAC NORTH AMERICA INC. ',
       'BRONCO WINE COMPANY        ', 'BROWN-FORMAN CORP          ',
       'BULLY BOY DISTILLERS       ', 'BLACK ROCK SPIRITS LLC     ',
       'CALEDONIA SPIRITS INC      ', 'CONSTELLATION BRANDS INC   ',
       'CAPSTONE INTERNATIONAL     ', 'CASTLE BRANDS CORP.        ',
       'VINEYARD BRANDS INC        ', 'VINEYARD BRANDS LLC        ',
       'DIAGEO CHATEAU ESTATE WINES', 'VRANKEN AMERICA            ',
       'Circa Wines                ', 'FABRIZIA SPIRITS LLC       ',
       'ALISA CARR BEVERAGES           ', 'SOUTHERN GLAZERS W&S OF NE ',
       'SOUTHERN WINE & SPIRITS NE ', 'DELICATO VINEYARDS INC     ',
       'BLACK PRINCE DISTILLERY INC', 'DJINN SPIRITS LLC          ',
       'DUGGANS DISTILLED PRODUCTS ', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS         ', 'CENTEUR IMPORTS LLC        ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'GILMANTON WINERY & VINEYARD', 'WILLIAM GRANT & SONS INC   ',
       'HEAVEN HILL DISTILLERIES   ', 'HOOD RIVER DISTILLERS, Inc.',
       'HIGHLAND WINE MERCHANTS LLC', 'DIAGEO NORTH AMERICA INC   ',
       'CHARLES JACQUIN ET CIE INC ', 'MARTIGNETTI COMPANIES',
       'MARTIGNETTI COMPANIES ', 'AMERICAN VINTAGE BEVERAGE  ',
       'KLIN SPIRITS LLC           ', 'KOBRAND CORPORATION        ',
       'LAIRD & CO                 ', 'LAUREATE IMPORTS CO        ',
       'LATITUDE BEVERAGE COMPANY  ', 'LOYAL DOG WINERY           ',
       'MANGO BOTTLING INC         ', 'MARSALLE COMPANY           ',
       'MILTONS DISTRIBUTING CO    ', 'MCCORMICK DISTILLING CO    ',
       'MHW LTD                    ', 'MOONLIGHT MEADERY          ',
       'UNCORKED       ', 'NICHE W & S                ',
       'OLE SMOKY DISTILLERY LLC   ', 'PALM BAY INTERNATIONAL INC ',
       'PARK STREET IMPORTS LLC    ', 'PINE STATE TRADING CO      ',
       'PREMIER DISTRIBUTORS       ', 'REMY COINTREAU USA INC     ',
       'PREMIUM PORT WINES, INC.   ', 'PROXIMO SPIRITS INC.       ',
       'PSP WINES ', 'R.P.IMPORTS INC            ',
       'SAZERAC CO INC             ', 'MOET HENNESSY USA INC      ',
       'SEA HAGG DISTILLERY LLC    ', 'SHAW ROSS INT L IMP LTD    ',
       'LUXCO INC                  ', 'STAR INDUSTRIES INC.       ',
       'STOLI GROUP,(USA) LLC      ', 'STE MICHELLE WINE ESTATES  ',
       'SURVILLE ENTERPRISES CORP  ', 'TRINCHERO FAMILY ESTATES   ',
       'TAKARA SAKE USA INC        ', 'TRUETT HURST               ',
       'ULTRA BEVERAGE COMPANY LLP ', 'PHILLIPS PRODUCTS CO.      ',
       'TY KU LLC                  ', 'M S WALKER INC             ',
       'WEIN BAUER INC             ', 'WESTERN SPIRITS BEVERAGE CO',
       'FREDERICK WILDMAN & SONS   ', 'VINEDREA WINES LLC         ',
       'WINE GROUP INC             ', 'TREASURY WINE ESTATES      ',
       'MAJESTIC FINE WINES        ', 'Russian Standard Vodka     ',
       'PERFECTA WINES             ', 'CAMPARI AMERICA            ',
       'STELLAR IMPORTING CO LLC   ', 'JIM BEAM BRANDS COMPANY    ',
       'FLAG HILL WINERY & VINEYARD', 'JEWELL TOWNE VINEYARDS     ',
       'SEA BREEZE CELLARS LLC     ', 'PERNOD RICARD USA          '],
      dtype=object)

1. The Volume is a numerical column but having object datatype.
2. There are some products that are not sold, so having missing values.
3. There are white spaces in the categorical columns.

In [29]:
# creating new columns for better analysis
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars'])*100
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']
vendor_sales_summary['SalesToPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [30]:
# changing datatype to float
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float')

# filling missing value with 0
vendor_sales_summary.fillna(0,inplace = True)

# removing spaces from categorical columns
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()
vendor_sales_summary['Description'] = vendor_sales_summary['Description'].str.strip()

### Saving Cleaned Data into Database

After completing data cleaning, the refined dataset is stored back into the database. This ensures that dashboards, reports, and analytics processes use accurate, consistent, and optimized data, reducing query time and improving overall performance.

In [31]:
cursor = conn.cursor()

In [35]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    Volume INT,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalesToPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);
""")

In [36]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists = 'replace', index = False )

10000

In [37]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

,VendorNumber,VendorName,Brand,Description,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,VendorNo,TotalSalesQuantity,TotalSalesDollars,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,Ch Lilian 09 Ladouys St Este,750.0,8,190.88,2.0,90.0,3329.10,3138.22,94.266318,11.250000,17.440801
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,Flavor Essence Variety 5 Pak,162.5,320,5440.00,2.0,120.0,2998.80,-2441.20,-81.405896,0.375000,0.551250
2,54,AAPER ALCOHOL & CHEMICAL CO,990,Ethyl Alcohol 200 Proof,3750.0,1,105.07,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
3,60,ADAMBA IMPORTS INTL INC,771,Bak's Krupnik Honey Liqueur,750.0,39,446.16,60.0,235.0,3522.65,3076.49,87.334535,6.025641,7.895486
4,60,ADAMBA IMPORTS INTL INC,3401,Vesica Vodka,1750.0,6,66.60,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17035,PERNOD RICARD USA,3389,Seagrams Extra Dry Gin,1750.0,13108,163718.92,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
9996,17035,PERNOD RICARD USA,3422,Beefeater,750.0,9667,154575.33,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
9997,17035,PERNOD RICARD USA,3423,Beefeater,1750.0,46163,980963.75,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
9998,17035,PERNOD RICARD USA,3425,Olmeca Altos Plata Tequila,750.0,4151,64548.05,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000
9999,17035,PERNOD RICARD USA,3457,Olmeca Altos Plata Tequila,1750.0,4187,93705.06,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000

## Final Data Preparation & Storage

The vendor sales summary dataset was successfully created by combining purchase, sales, pricing, and freight data to generate vendor-level performance metrics. The data was cleaned to ensure consistency, accuracy, and reliability by handling missing values, correcting data types, and standardizing categorical fields.

The final processed dataset was stored in the database to support faster querying, efficient dashboarding, and future analytical reporting. Storing the aggregated dataset reduces computational overhead by avoiding repeated heavy joins and aggregations on raw transactional tables.

### Key Benefits
- Improves query performance and reduces processing time.
- Enables efficient vendor profitability and pricing analysis.
- Supports scalable dashboard and reporting workflows.
- Provides a structured dataset for business decision-making and optimization.

This dataset serves as a foundation for further analytical insights, performance monitoring, and strategic vendor selection.